refactored-group/bigcommerce-checkout-js

cloudbuild.yaml

Adds HOST and GOOGLE_MAPS_KEY variables in cloudbuild.yaml

---

packages/core/src/app/checkout/dealer/DealerShipping.scss
packages/core/src/app/checkout/dealer/DealerShipping.tsx
packages/core/src/app/checkout/dealer/Locator.tsx

FRM-116 adds multi shipment feature

---

packages/core/src/app/checkout/dealer/Locator.tsx

FRM-129 fixes issue when searching with empty location text box

---

packages/core/src/app/checkout/dealer/DealerShipping.tsx

FFL-169 removes unnecessary address initialization

---

packages/core/src/app/checkout/dealer/DealerShipping.scss
packages/core/src/app/checkout/dealer/Map.tsx
packages/core/src/app/checkout/dealer/PhoneNumberFormatter.tsx
packages/core/src/app/checkout/dealer/locator/DealerCard.tsx

[FFL-185 - Add Formatted Phone Number to Automatic FFL Checkout and Ad…](https://github.com/refactored-group/bigcommerce-checkout-js/commit/1ea508bdafcd962a4a59335592ed5365c159acff)
[Fix coding standards - Explicit Variable Type to 'any'](https://github.com/refactored-group/bigcommerce-checkout-js/commit/4c9ba62d543bcdc876c58a684ae58876d0a29047)
[Refactoring for Phone Number Formatter](https://github.com/refactored-group/bigcommerce-checkout-js/commit/2df3e67a54522cd6980df8fc44b440af5f1d0555)

Ffl 1.273 stage

---

packages/core/src/app/checkout/dealer/Locator.tsx
packages/core/src/scss/components/checkout/checkoutSteps/_locator.scss

FFL-267 updates 'show' css class to accomdate interference

---

packages/core/src/app/checkout/dealer/locator/Fees.tsx
packages/core/src/scss/components/checkout/checkoutSteps/_locator.scss

Release PR: FFL-262 updates dealer fees and schedules scss

---

packages/core/src/app/checkout/Checkout.tsx
packages/core/src/app/checkout/dealer/DealerShipping.tsx
packages/core/src/app/order/updateOrderStaffNotes.ts
packages/core/src/app/payment/Payment.tsx

FFL-290 adds staff notes to order upon order confirmation

---

packages/core/src/app/checkout/dealer/DealerShipping.tsx

FFL-293 fixes error when selecting address for bundled non ffl items

---

packages/core/src/app/checkout/dealer/DealerShipping.tsx

Release PR: FFL-293 fixes error when selecting address for bundled non ffl items

---

packages/core/src/app/checkout/Checkout.tsx
packages/core/src/app/checkout/dealer/CustomShippingForm.scss
packages/core/src/app/checkout/dealer/CustomShippingForm.tsx
packages/core/src/app/checkout/dealer/DealerShipping.tsx
packages/core/src/app/checkout/dealer/StatesDropdown.tsx
packages/core/src/app/shipping/getFflLineItems.tsx

FRM-223 addres ammo feature

---

packages/core/src/app/checkout/Checkout.tsx
packages/core/src/app/checkout/dealer/CustomShippingForm.tsx
packages/core/src/app/checkout/dealer/DealerShipping.tsx
packages/core/src/app/checkout/dealer/StatesDropdown.tsx

FRM-240 adds checking for ammo subscription

---

packages/core/src/app/checkout/Checkout.tsx
packages/core/src/app/checkout/dealer/CustomShippingForm.scss
packages/core/src/app/checkout/dealer/CustomShippingForm.tsx
packages/core/src/app/checkout/dealer/DealerShipping.tsx
packages/core/src/app/checkout/dealer/StatesDropdown.tsx
packages/core/src/app/shipping/getFflLineItems.tsx

Release PR: FRM-223 adds ammo feature

---

packages/core/src/app/shipping/getFflLineItems.tsx

FRM-241 updates custom field lookup for ammo items

---

packages/core/src/app/checkout/Checkout.tsx
packages/core/src/app/checkout/dealer/CustomShippingForm.tsx
packages/core/src/app/checkout/dealer/DealerShipping.tsx
packages/core/src/app/checkout/dealer/StatesDropdown.tsx
packages/core/src/app/shipping/getFflLineItems.tsx

Release PR:  FRM-241, FRM-240

---

packages/core/src/app/checkout/dealer/DealerShipping.tsx

FRM-238 fixes autofill not triggering shipping fee estimates on checkout

---

packages/core/src/app/checkout/dealer/DealerShipping.tsx

Release PR: FRM-238 fixes autofill not triggering shipping fee estimates on checkout

---

packages/core/src/app/checkout/Checkout.tsx
packages/core/src/app/checkout/dealer/DealerShipping.tsx
packages/core/src/app/shipping/getFflLineItems.tsx

...
...
...
@bigcommerce/team-checkout

Release anton

---

packages/core/src/app/checkout/Checkout.tsx

...
...
...
@bigcommerce/team-checkout

FFL-322 fixes checkout error when only digital items are on the cart

---

packages/core/src/app/checkout/Checkout.tsx

...
...
...
@bigcommerce/team-checkout

Release PR: FFL-322 fixes checkout error when only digital items are on the cart
